#!/usr/bin/env python3
"""Generate human-readable use-case-report.md from use-case-tree.json.

CLI: python3 cr_gen_usecase_report.py <base_path>

Reads use-case-tree.json → produces use-case-report.md.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from _common import (
    require_json,
    ensure_list,
    now_iso,
    write_markdown,
)


def generate_usecase_report(base_path):
    """Generate use-case-report.md from use-case-tree.json."""
    uc_dir = os.path.join(base_path, ".allforai", "use-case")
    tree_data = require_json(os.path.join(uc_dir, "use-case-tree.json"), "use-case-tree")

    roles = ensure_list(tree_data, "roles")

    lines = []
    lines.append("# Use Case Report")
    lines.append("")
    lines.append(f"> Generated by code-replicate | {now_iso()}")
    lines.append("")

    total_count = 0
    role_count = 0
    area_set = set()

    for role in roles:
        role_name = role.get("role_name", role.get("name", "Unknown"))
        features = ensure_list(role, "features")
        if not features and not role_name:
            continue
        role_count += 1

        lines.append(f"## {role_name}")
        lines.append("")

        for feature in features:
            area = feature.get("area", feature.get("name", "Unknown"))
            area_set.add(area)
            use_cases = ensure_list(feature, "use_cases")

            lines.append(f"### {area}")
            lines.append("")
            lines.append("| ID | Title | Type | Priority |")
            lines.append("|----|-------|------|----------|")

            for uc in use_cases:
                uc_id = uc.get("id", "")
                title = uc.get("title", "")
                uc_type = uc.get("type", "")
                priority = uc.get("priority", "")
                lines.append(f"| {uc_id} | {title} | {uc_type} | {priority} |")
                total_count += 1

            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"**Summary:** {total_count} use cases across {role_count} roles, {len(area_set)} feature areas")
    lines.append("")

    content = "\n".join(lines)
    output_path = os.path.join(uc_dir, "use-case-report.md")
    write_markdown(output_path, content)

    print(f"Generated use-case report ({total_count} use cases) → {output_path}", file=sys.stderr)
    return output_path


def main():
    if len(sys.argv) < 2:
        print("Usage: cr_gen_usecase_report.py <base_path>", file=sys.stderr)
        sys.exit(1)
    generate_usecase_report(sys.argv[1])


if __name__ == "__main__":
    main()
